name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y meson valgrind
    - run: |
       meson _build
       cd _build
       ninja
       ninja test
       meson test --setup=valgrind

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install meson
    - run: |
       meson _build
       cd _build
       ninja
       ninja test


