name: C/C++ CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'docs/**'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir _build
    - run: cmake -B _build
    - run: make -C _build all test
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir _build
    - run: cmake -B _build
    - run: make -C _build all test
