name: C/C++ CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: trunk
    paths:
    - '**'
    - '!**.md'
    - '!docs/**'
    - '!**.yml'
    - '**/c-cpp.yml'
  pull_request:
    branches: trunk
    paths:
    - '**'
    - '!**.md'
    - '!docs/**'
    - '!**.yml'
    - '**/c-cpp.yml'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc-9, gcc-11, clang-13, clang-14]
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # sudo apt remove -y firefox
        sudo apt update
        # sudo apt upgrade -y
        sudo apt install -y meson ninja-build $CC

    - name: Build
      run: |
       meson setup _build -Db_sanitize=address,undefined -Db_lundef=false
       cd _build
       ninja
    - name: Test
      run: cd _build && meson test -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: brew install meson
    - run: |
       meson setup _build -Db_sanitize=address,undefined -Db_lundef=false
       cd _build
       ninja
       meson test -v
