name: C/C++ CI

on:
  push:
    branches: trunk
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.github/workflows/codeql-analysis.yml'
  pull_request:
    branches: trunk
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.github/workflows/codeql-analysis.yml'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y meson valgrind
    - run: |
       meson _build
       cd _build
       ninja
       ninja test
       meson test --setup=valgrind

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install meson
    - run: |
       meson _build
       cd _build
       ninja
       ninja test


