name: C/C++ CI
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: trunk
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.github/workflows/codeql-analysis.yml'
  pull_request:
    branches: trunk
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - '.github/workflows/codeql-analysis.yml'

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y meson
    - run: |
       meson _build
       cd _build
       ninja
       meson test -v

  ubuntu-jammy:
    runs-on: ubuntu-22.04
    env:
      CC: 'gcc-12'
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y meson $CC
    - run: |
       meson _build
       cd _build
       ninja
       meson test -v

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: brew install meson
    - run: |
       meson _build
       cd _build
       ninja
       ninja test

  freebsd:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        usesh: true
        prepare: pkg install -y meson ninja
        run: |
         meson _build
         cd _build
         ninja test

